/* config.h.  Generated by configure.  */
/* config.h.in.  Generated from configure.in by autoheader.  */

/* Define to 1 if you want to include debug code in the library */
/* #undef DEBUG */

/* Define to 1 */
#define FRIBIDI_EXPORTS 1

/* Define to 1 if you do not want character set conversion routines */
/* #undef FRIBIDI_NO_CHARSETS */

/* */
#define HAS_FRIBIDI_TAB_CHAR_TYPE_2_I 1

/* */
/* #undef HAS_FRIBIDI_TAB_CHAR_TYPE_3_I */

/* */
/* #undef HAS_FRIBIDI_TAB_CHAR_TYPE_4_I */

/* */
/* #undef HAS_FRIBIDI_TAB_CHAR_TYPE_5_I */

/* */
/* #undef HAS_FRIBIDI_TAB_CHAR_TYPE_6_I */

/* */
/* #undef HAS_FRIBIDI_TAB_CHAR_TYPE_7_I */

/* */
/* #undef HAS_FRIBIDI_TAB_CHAR_TYPE_8_I */

/* */
#define HAS_FRIBIDI_TAB_CHAR_TYPE_9_I 1

/* Define to 1 if you have the <dlfcn.h> header file. */
#define HAVE_DLFCN_H 1

/* Define to 1 if you have the <inttypes.h> header file. */
#define HAVE_INTTYPES_H 1

/* Define to 1 if you have the <memory.h> header file. */
#define HAVE_MEMORY_H 1

/* Define to 1 if you have the <stdint.h> header file. */
#define HAVE_STDINT_H 1

/* Define to 1 if you have the <stdlib.h> header file. */
#define HAVE_STDLIB_H 1

/* Define to 1 if you have the <strings.h> header file. */
#define HAVE_STRINGS_H 1

/* Define to 1 if you have the <string.h> header file. */
#define HAVE_STRING_H 1

/* Define to 1 if you have the <sys/stat.h> header file. */
#define HAVE_SYS_STAT_H 1

/* Define to 1 if you have the <sys/types.h> header file. */
#define HAVE_SYS_TYPES_H 1

/* Define to 1 if you have the <unistd.h> header file. */
#define HAVE_UNISTD_H 1

/* Define to 1 if you want to optimize for memory instead of speed */
/* #undef MEM_OPTIMIZED */

/* Name of package */
#define PACKAGE "fribidi"

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT "http://fribidi.org/bug"

/* Define to the full name of this package. */
#define PACKAGE_NAME "GNU FriBidi"

/* Define to the full name and version of this package. */
#define PACKAGE_STRING "GNU FriBidi 0.10.7"

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME "fribidi"

/* Define to the version of this package. */
#define PACKAGE_VERSION "0.10.7"

/* The size of a `int', as computed by sizeof. */
//#define SIZEOF_INT 4
#define SIZEOF_INT sizeof(int)

/* The size of a `long', as computed by sizeof. */
//#define SIZEOF_LONG 4
#define SIZEOF_LONG sizeof(long)

/* The size of a `short', as computed by sizeof. */
//#define SIZEOF_SHORT 2
#define SIZEOF_SHORT sizeof(short)

/* Define to 1 if you have the ANSI C header files. */
#define STDC_HEADERS 1

/* Define to 1 if you prefer simple malloc instead of chunk memory */
/* #undef USE_SIMPLE_MALLOC */

/* Version number of package */
#define VERSION "0.10.7"
