/*
 *     Generated by class-dump (version 2.1.5).
 *
 *     class-dump is Copyright (C) 1997, 1999, 2000, 2001 by Steve Nygard.
 */

/*
 * File: ImageKit (/System/Library/Frameworks/Quartz.framework/Frameworks/ImageKit.framework - Mac OS X 10.5.0)
 */

@protocol IKImageProxy;

@interface IKPictureTakerRecentPicture:NSObject
{
}

+ defaultRecentPictureWithImageWrapper:fp8 cropSize:(NSSize)size;
+ defaultRecentPictureWithOriginalData:fp8 cropSize:(NSSize)size;
+ defaultRecentPictureWithOriginalImage:fp8 cropSize:(NSSize)size;
+ emptyRecentPictureWithIcon:fp8;
- _infoToSaveInRepository:fp8;
- cropInfo;
- (NSSize)cropSize;
- (void)dealloc;
- (NSImage *)editedImage;
- (void)finalize;
- initWithInfo:fp8 withRepository:fp12;
- initWithOriginalImage:fp8 cropSize:(NSSize)size cropInfo:fp20 smallIcon:fp24;
- (BOOL)isABMeImage;
- (BOOL)isEmpty;
- (NSImage *)originalImage;
- (NSString *)originalImageName;
- (NSString *)originalImagePath;
- (void)setCropInfo:fp8 smallIcon:fp12;
- (void)setCropSize:(NSSize)fp8;
- (void)setIsABMeImage:(BOOL)fp8;
- (void)setIsEmpty:(BOOL)fp8;
- (void)setOriginalImagePath:fp8;
- (void)setTimeValue:(double)fp8;
- (void)setUserInfo:(void *)fp8;
- (NSImage *)smallIcon;
- (double)timeValue;
- (void)upgradeForCropSize:(NSSize)size;
- (void *)userInfo;
- (NSInteger)version;

@end

@interface IKPictureTakerRecentPictureRepository:NSObject
{
}

+ domainName;
+ recentRepository;
+ recentRepositoryWithDomainName:fp8;
+ (void)setDomainName:fp8;
- _infoFilePath;
- (void)addRecent:fp8;
- (void)clearRecents:(id)sender;
- (void)dealloc;
- initWithDomainName:fp8;
- (void)loadRecentsIfNeeded;
- (NSInteger)maxRecents;
- originalImagePathForRecent:fp8;
- pictureDirPath;
- (char)purgeExtras;
- recentPictures;
- (void)removeRecent:fp8;
- (void)saveChanges;
- (void)setRecentPictureAsCurrent:fp8;
- (void)updateRecentPicture:fp8 setCropInfo:fp12 smallIcon:fp16;

@end

